### ISSUE TITLE
rebar3 compatibility

### ISSUE THREAD

**Issue by hachreak** [erlangbureau/liver#1]
Hi at all,
I'm trying to use `liver` in my `rebar3` project.
I made a [commit](https://github.com/hachreak/liver/tree/rebar3) to make the project compatible with rebar3.
If you are interested, we can work together to integrate in your repo. :smile:

**Comment by kostiushkin** [comment]
Hi, I don't use rebar3, Is the project realy incompatible with rebar3?

**Comment by hachreak** [comment]
I think that there are some "small fix" about have a `liver.app.src` and `rebar.config` files.
And a bit more tricky fix to specify the relative path of `LIVR test_suite` inside the tests (because `erlang.mk` put everything in `deps` and `rebar3` put all in `_build/default/lib`).
In latter issue we should find a better solution (or we could leave tests only for `erlang.mk`).
You can find all changes inside the commit.

**Comment by kostiushkin** [comment]
Ok, I'll take a look

**Comment by hachreak** [comment]
thanks :smile:

**Comment by kostiushkin** [comment]
Fixed in ede48e9. Try it now
