### ISSUE TITLE
Support for unicode characters

### ISSUE THREAD

**Issue by gwelr** [erlangbureau/liver#3]
Is liver supporting unicode characters ? 
I have made a simple test which shows there might be an issue in the validators when unicode characters are used. 

Example: 
```erl
11> Schema1 = [{<<"first_name">>,[{length_between,[4,6]}]}].
[{<<"first_name">>,[{length_between,[4,6]}]}]
12> Input5 = [{<<"first_name">>,<<"Grego">>}].
[{<<"first_name">>,<<"Grego">>}]
13> liver:validate(Schema1, Input5).          
{ok,[{<<"first_name">>,<<"Grego">>}]}
14> Input6 = [{<<"first_name">>,<<"Grégo">>}].
[{<<"first_name">>,<<"Grégo">>}]
15> liver:validate(Schema1, Input6).          
{error,[{<<"first_name">>,<<"FORMAT_ERROR">>}]}
```
The only difference between Input5 and Input6 is the `é` character used in the first_name of Input6 compared to the first_name of Input5.

Or maybe I'm doing something wrong (I'm rather new to erlang). In this case, sorry for bothering you.

**Comment by kostiushkin** [comment]
Yes, supports.
You get an error because your string is not really Unicode.

Try this:
```
1> Schema = [{<<"first_name">>,[{length_between,[4,6]}]}].
[{<<"first_name">>,[{length_between,[4,6]}]}]
2> Input = [{<<"first_name">>,<<"Grégo"/utf8>>}].
[{<<"first_name">>,<<"Grégo">>}]
3> liver:validate(Schema, Input).                        
{ok,[{<<"first_name">>,<<"Grégo"/utf8>>}]}
```
